[2024-10-03T04:45:04.382+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:45:04.385+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:45:04.395+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:45:04.395+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:45:11.241+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:45:11.220+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:45:11.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:45:11.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 7.003 seconds
[2024-10-03T04:45:42.701+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:45:42.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:45:42.859+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:45:42.844+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:45:55.995+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:45:55.980+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:45:55.999+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:45:56.045+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 13.504 seconds
[2024-10-03T04:46:26.580+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:46:26.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:46:26.628+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:46:26.628+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:46:29.867+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:46:29.847+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:46:29.871+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:46:30.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 3.518 seconds
[2024-10-03T04:47:00.726+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:47:00.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:47:00.741+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:47:00.740+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:47:02.587+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:47:02.574+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:47:02.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:47:02.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 2.010 seconds
[2024-10-03T04:47:33.321+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:47:33.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:47:33.343+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:47:33.342+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:47:34.857+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:47:34.847+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:47:34.861+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:47:34.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.608 seconds
[2024-10-03T04:48:05.598+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:48:05.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:48:05.609+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:48:05.608+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:48:06.744+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:48:06.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:48:06.747+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:48:06.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.217 seconds
[2024-10-03T04:48:37.483+0000] {processor.py:157} INFO - Started process (PID=62) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:48:37.485+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:48:37.489+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:48:37.488+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:48:38.525+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:48:38.514+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:48:38.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:48:38.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.100 seconds
[2024-10-03T04:49:09.222+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:49:09.226+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:49:09.235+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:49:09.233+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:49:10.174+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:49:10.161+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:49:10.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:49:10.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.051 seconds
[2024-10-03T04:49:40.823+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:49:40.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:49:40.831+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:49:40.830+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:49:41.532+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:49:41.515+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:49:41.535+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:49:41.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.783 seconds
[2024-10-03T04:50:12.136+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:50:12.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:50:12.141+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:50:12.141+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:50:12.600+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:50:12.592+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:50:12.602+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:50:12.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.526 seconds
[2024-10-03T04:50:43.210+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:50:43.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:50:43.221+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:50:43.220+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:50:43.938+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:50:43.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:50:43.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:50:43.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.796 seconds
[2024-10-03T04:51:14.678+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:51:14.685+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:51:14.723+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:51:14.719+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:51:17.414+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:51:17.393+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:51:17.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:51:17.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 2.960 seconds
[2024-10-03T04:51:47.830+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:51:47.833+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:51:47.838+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:51:47.838+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:51:48.697+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:51:48.674+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:51:48.701+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:51:48.762+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.939 seconds
[2024-10-03T04:52:19.406+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:52:19.410+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:52:19.417+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:52:19.416+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:52:20.222+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:52:20.208+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:52:20.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:52:20.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.882 seconds
[2024-10-03T04:52:50.700+0000] {processor.py:157} INFO - Started process (PID=97) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:52:50.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:52:50.713+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:52:50.712+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:52:51.561+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:52:51.546+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:52:51.565+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:52:51.613+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.926 seconds
[2024-10-03T04:53:22.030+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:53:22.033+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:53:22.038+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:53:22.037+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:53:22.645+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:53:22.634+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:53:22.648+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:53:22.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.664 seconds
[2024-10-03T04:53:53.126+0000] {processor.py:157} INFO - Started process (PID=105) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:53:53.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:53:53.135+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:53:53.134+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:53:54.060+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:53:54.049+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:53:54.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:53:54.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.042 seconds
[2024-10-03T04:54:24.651+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:54:24.653+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:54:24.658+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:54:24.657+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:54:25.266+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:54:25.256+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:54:25.268+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:54:25.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.672 seconds
[2024-10-03T04:54:55.531+0000] {processor.py:157} INFO - Started process (PID=113) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:54:55.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:54:55.542+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:54:55.541+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:54:56.228+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:54:56.215+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:54:56.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:54:56.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.754 seconds
[2024-10-03T04:55:26.540+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:55:26.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:55:26.550+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:55:26.549+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:55:27.265+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:55:27.251+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:55:27.268+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:55:27.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.779 seconds
[2024-10-03T04:55:57.760+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:55:57.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:55:57.768+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:55:57.767+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:55:58.499+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:55:58.486+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:55:58.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:55:58.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.789 seconds
[2024-10-03T04:56:28.839+0000] {processor.py:157} INFO - Started process (PID=125) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:56:28.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:56:28.846+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:56:28.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:56:29.458+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:56:29.448+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:56:29.461+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:56:29.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.679 seconds
[2024-10-03T04:56:59.939+0000] {processor.py:157} INFO - Started process (PID=129) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:56:59.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:56:59.947+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:56:59.946+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:57:00.643+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:57:00.610+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:57:00.647+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:57:00.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.764 seconds
[2024-10-03T04:57:31.255+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:57:31.258+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:57:31.265+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:57:31.264+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:57:32.114+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:57:32.100+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:57:32.117+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:57:32.171+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.925 seconds
[2024-10-03T04:58:02.735+0000] {processor.py:157} INFO - Started process (PID=137) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:58:02.737+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:58:02.744+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:58:02.743+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:58:03.352+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:58:03.342+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:58:03.356+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:58:03.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.664 seconds
[2024-10-03T04:58:33.819+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:58:33.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:58:33.827+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:58:33.826+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:58:34.495+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:58:34.483+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:58:34.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:58:34.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.743 seconds
[2024-10-03T04:59:04.905+0000] {processor.py:157} INFO - Started process (PID=145) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:59:04.908+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:59:04.914+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:59:04.913+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:59:05.884+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:59:05.863+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:59:05.887+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:59:05.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.100 seconds
[2024-10-03T04:59:36.243+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T04:59:36.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T04:59:36.253+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:59:36.252+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:59:36.960+0000] {logging_mixin.py:151} INFO - [2024-10-03T04:59:36.947+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T04:59:36.963+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T04:59:37.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.830 seconds
[2024-10-03T05:00:07.863+0000] {processor.py:157} INFO - Started process (PID=153) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:00:07.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:00:07.873+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:00:07.873+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:00:08.549+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:00:08.534+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:00:08.553+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:00:08.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.760 seconds
[2024-10-03T05:00:39.102+0000] {processor.py:157} INFO - Started process (PID=157) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:00:39.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:00:39.115+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:00:39.113+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:00:39.848+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:00:39.838+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:00:39.852+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:00:39.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.822 seconds
[2024-10-03T05:01:10.229+0000] {processor.py:157} INFO - Started process (PID=161) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:01:10.232+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:01:10.238+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:01:10.237+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:01:10.957+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:01:10.944+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:01:10.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:01:11.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.787 seconds
[2024-10-03T05:01:41.287+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:01:41.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:01:41.301+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:01:41.297+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:01:42.133+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:01:42.118+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:01:42.137+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:01:42.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.918 seconds
[2024-10-03T05:02:12.582+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:02:12.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:02:12.588+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:02:12.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:02:13.178+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:02:13.168+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:02:13.181+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:02:13.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.635 seconds
[2024-10-03T05:02:43.456+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:02:43.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:02:43.466+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:02:43.465+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:02:44.175+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:02:44.164+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:02:44.179+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:02:44.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.782 seconds
[2024-10-03T05:03:14.711+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:03:14.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:03:14.791+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:03:14.790+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:03:15.475+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:03:15.463+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:03:15.482+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:03:15.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.820 seconds
[2024-10-03T05:03:45.864+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:03:45.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:03:45.874+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:03:45.873+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:03:46.590+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:03:46.578+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:03:46.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:03:46.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.792 seconds
[2024-10-03T05:04:16.988+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:04:16.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:04:16.996+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:04:16.996+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:04:17.699+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:04:17.685+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:04:17.703+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:04:17.739+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.763 seconds
[2024-10-03T05:04:48.305+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:04:48.308+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:04:48.314+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:04:48.314+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:04:49.107+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:04:49.095+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:04:49.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:04:49.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.870 seconds
[2024-10-03T05:05:19.358+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:05:19.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:05:19.366+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:05:19.366+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:05:19.952+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:05:19.942+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:05:19.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:05:20.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.654 seconds
[2024-10-03T05:05:50.380+0000] {processor.py:157} INFO - Started process (PID=197) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:05:50.384+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:05:50.390+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:05:50.389+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:05:51.052+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:05:51.040+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:05:51.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:05:51.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.722 seconds
[2024-10-03T05:06:21.334+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:06:21.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:06:21.341+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:06:21.341+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:06:22.136+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:06:22.123+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:06:22.140+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:06:22.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.854 seconds
[2024-10-03T05:06:52.685+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:06:52.687+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:06:52.692+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:06:52.691+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:06:53.257+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:06:53.248+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:06:53.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:06:53.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.627 seconds
[2024-10-03T05:07:23.469+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:07:23.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:07:23.480+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:07:23.480+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:07:24.135+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:07:24.122+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:07:24.138+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:07:24.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.716 seconds
[2024-10-03T05:07:54.624+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:07:54.627+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:07:54.633+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:07:54.632+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:07:55.468+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:07:55.454+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:07:55.471+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:07:55.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.885 seconds
[2024-10-03T05:08:25.883+0000] {processor.py:157} INFO - Started process (PID=217) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:08:25.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:08:25.890+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:08:25.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:08:26.620+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:08:26.606+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:08:26.624+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:08:26.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.803 seconds
[2024-10-03T05:08:56.896+0000] {processor.py:157} INFO - Started process (PID=221) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:08:56.899+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:08:56.906+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:08:56.905+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:08:57.681+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:08:57.670+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:08:57.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:08:57.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.861 seconds
[2024-10-03T05:09:28.218+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:09:28.221+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:09:28.228+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:09:28.227+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:09:28.874+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:09:28.863+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:09:28.877+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:09:28.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.707 seconds
[2024-10-03T05:09:59.192+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:09:59.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:09:59.200+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:09:59.199+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:09:59.872+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:09:59.861+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:09:59.876+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:09:59.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.753 seconds
[2024-10-03T05:10:30.561+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:10:30.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:10:30.570+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:10:30.570+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:10:31.205+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:10:31.196+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:10:31.209+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:10:31.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.693 seconds
[2024-10-03T05:11:01.618+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:11:01.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:11:01.630+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:11:01.629+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:11:02.495+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:11:02.480+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:11:02.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:11:02.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.948 seconds
[2024-10-03T05:11:32.699+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:11:32.703+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:11:32.710+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:11:32.709+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:11:33.337+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:11:33.327+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:11:33.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:11:33.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.692 seconds
[2024-10-03T05:12:03.487+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:12:03.489+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:12:03.494+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:12:03.493+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:12:04.105+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:12:04.093+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:12:04.109+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:12:04.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.650 seconds
[2024-10-03T05:12:34.276+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:12:34.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:12:34.285+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:12:34.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:12:34.948+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:12:34.937+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:12:34.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:12:35.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.747 seconds
[2024-10-03T05:13:05.401+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:13:05.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:13:05.407+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:13:05.407+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:13:06.096+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:13:06.086+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:13:06.100+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:13:06.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.756 seconds
[2024-10-03T05:13:36.456+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:13:36.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:13:36.469+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:13:36.468+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:13:37.216+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:13:37.202+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:13:37.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:13:37.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.832 seconds
[2024-10-03T05:14:07.757+0000] {processor.py:157} INFO - Started process (PID=261) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:14:07.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:14:07.764+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:14:07.764+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:14:08.363+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:14:08.351+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:14:08.367+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:14:08.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.656 seconds
[2024-10-03T05:14:38.648+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:14:38.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:14:38.659+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:14:38.658+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:14:39.315+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:14:39.304+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:14:39.319+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:14:39.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.733 seconds
[2024-10-03T05:15:09.671+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:15:09.673+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:15:09.678+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:15:09.677+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:15:10.287+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:15:10.275+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:15:10.290+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:15:10.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.665 seconds
[2024-10-03T05:15:40.807+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:15:40.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:15:40.815+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:15:40.814+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:15:41.417+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:15:41.405+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:15:41.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:15:41.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.675 seconds
[2024-10-03T05:16:11.865+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:16:11.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:16:11.874+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:16:11.873+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:16:12.707+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:16:12.695+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:16:12.711+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:16:12.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.901 seconds
[2024-10-03T05:16:43.324+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:16:43.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:16:43.333+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:16:43.333+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:16:43.976+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:16:43.964+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:16:43.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:16:44.029+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.711 seconds
[2024-10-03T05:17:14.509+0000] {processor.py:157} INFO - Started process (PID=285) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:17:14.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:17:14.520+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:17:14.519+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:17:15.370+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:17:15.357+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:17:15.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:17:15.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.915 seconds
[2024-10-03T05:17:45.870+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:17:45.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:17:45.878+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:17:45.877+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:17:46.451+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:17:46.440+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:17:46.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:17:46.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.637 seconds
[2024-10-03T05:18:16.791+0000] {processor.py:157} INFO - Started process (PID=293) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:18:16.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:18:16.799+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:18:16.798+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:18:17.459+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:18:17.444+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:18:17.463+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:18:17.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.754 seconds
[2024-10-03T05:18:48.044+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:18:48.048+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:18:48.054+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:18:48.053+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:18:48.624+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:18:48.614+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:18:48.628+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:18:48.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.643 seconds
[2024-10-03T05:19:19.026+0000] {processor.py:157} INFO - Started process (PID=301) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:19:19.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:19:19.039+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:19:19.038+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:19:19.743+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:19:19.733+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:19:19.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:19:19.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.782 seconds
[2024-10-03T05:19:50.276+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:19:50.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:19:50.284+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:19:50.283+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:19:50.890+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:19:50.879+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:19:50.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:19:50.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.662 seconds
[2024-10-03T05:20:21.299+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:20:21.303+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:20:21.309+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:20:21.309+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:20:22.119+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:20:22.105+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:20:22.125+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:20:22.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.896 seconds
[2024-10-03T05:20:52.746+0000] {processor.py:157} INFO - Started process (PID=313) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:20:52.748+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:20:52.754+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:20:52.753+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:20:53.466+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:20:53.445+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:20:53.473+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:20:53.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.793 seconds
[2024-10-03T05:21:24.088+0000] {processor.py:157} INFO - Started process (PID=317) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:21:24.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:21:24.102+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:21:24.101+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:21:24.695+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:21:24.684+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:21:24.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:21:24.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.652 seconds
[2024-10-03T05:21:55.273+0000] {processor.py:157} INFO - Started process (PID=321) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:21:55.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:21:55.346+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:21:55.343+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:21:57.019+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:21:56.998+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:21:57.022+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:21:57.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.946 seconds
[2024-10-03T05:22:27.715+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:22:27.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:22:27.722+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:22:27.722+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:22:28.565+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:22:28.534+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:22:28.568+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:22:28.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.977 seconds
[2024-10-03T05:22:59.203+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:22:59.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:22:59.214+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:22:59.213+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:22:59.894+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:22:59.883+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:22:59.898+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:22:59.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.751 seconds
[2024-10-03T05:23:30.548+0000] {processor.py:157} INFO - Started process (PID=333) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:23:30.553+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:23:30.560+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:23:30.559+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:23:31.256+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:23:31.244+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:23:31.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:23:31.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.760 seconds
[2024-10-03T05:24:01.909+0000] {processor.py:157} INFO - Started process (PID=337) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:24:01.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:24:01.921+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:24:01.920+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:24:02.714+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:24:02.699+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:24:02.718+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:24:02.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.893 seconds
[2024-10-03T05:24:33.333+0000] {processor.py:157} INFO - Started process (PID=341) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:24:33.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:24:33.342+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:24:33.341+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:24:33.956+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:24:33.943+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:24:33.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:24:34.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.674 seconds
[2024-10-03T05:25:04.582+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:25:04.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:25:04.589+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:25:04.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:25:05.201+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:25:05.189+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:25:05.205+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:25:05.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.679 seconds
[2024-10-03T05:25:35.881+0000] {processor.py:157} INFO - Started process (PID=349) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:25:35.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:25:35.905+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:25:35.904+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:25:36.710+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:25:36.697+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:25:36.713+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:25:36.774+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.900 seconds
[2024-10-03T05:26:07.220+0000] {processor.py:157} INFO - Started process (PID=353) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:26:07.223+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:26:07.231+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:26:07.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:26:07.978+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:26:07.966+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:26:07.981+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:26:08.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.807 seconds
[2024-10-03T05:26:38.481+0000] {processor.py:157} INFO - Started process (PID=357) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:26:38.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:26:38.488+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:26:38.487+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:26:39.071+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:26:39.060+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:26:39.074+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:26:39.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.664 seconds
[2024-10-03T05:27:09.363+0000] {processor.py:157} INFO - Started process (PID=361) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:27:09.367+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:27:09.374+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:27:09.373+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:27:10.109+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:27:10.098+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:27:10.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:27:10.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.801 seconds
[2024-10-03T05:27:40.789+0000] {processor.py:157} INFO - Started process (PID=365) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:27:40.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:27:40.798+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:27:40.798+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:27:41.463+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:27:41.451+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:27:41.467+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:27:41.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.737 seconds
[2024-10-03T05:28:12.082+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:28:12.085+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:28:12.092+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:28:12.091+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:28:12.838+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:28:12.825+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:28:12.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:28:12.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.814 seconds
[2024-10-03T05:28:43.519+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:28:43.524+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:28:43.534+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:28:43.532+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:28:44.222+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:28:44.210+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:28:44.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:28:44.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.778 seconds
[2024-10-03T05:29:14.647+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:29:14.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:29:14.654+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:29:14.653+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:29:15.285+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:29:15.273+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:29:15.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:29:15.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.687 seconds
[2024-10-03T05:29:45.437+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:29:45.440+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:29:45.445+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:29:45.444+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:29:46.082+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:29:46.067+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:29:46.087+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:29:46.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.720 seconds
[2024-10-03T05:30:16.475+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:30:16.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:30:16.486+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:30:16.484+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:30:17.043+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:30:17.030+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:30:17.067+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:30:17.099+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.634 seconds
[2024-10-03T05:30:47.743+0000] {processor.py:157} INFO - Started process (PID=389) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:30:47.746+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:30:47.753+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:30:47.752+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:30:48.332+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:30:48.320+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:30:48.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:30:48.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.652 seconds
[2024-10-03T05:31:18.590+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:31:18.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:31:18.597+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:31:18.596+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:31:19.366+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:31:19.353+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:31:19.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:31:19.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.835 seconds
[2024-10-03T05:31:50.028+0000] {processor.py:157} INFO - Started process (PID=397) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:31:50.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:31:50.042+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:31:50.041+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:31:50.787+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:31:50.770+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:31:50.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:31:50.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.856 seconds
[2024-10-03T05:32:21.283+0000] {processor.py:157} INFO - Started process (PID=401) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:32:21.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:32:21.294+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:32:21.293+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:32:21.921+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:32:21.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:32:21.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:32:21.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.695 seconds
[2024-10-03T05:32:52.296+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:32:52.299+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:32:52.304+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:32:52.304+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:32:52.911+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:32:52.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:32:52.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:32:52.947+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.658 seconds
[2024-10-03T05:33:23.330+0000] {processor.py:157} INFO - Started process (PID=409) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:33:23.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:33:23.339+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:33:23.338+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:33:24.015+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:33:23.997+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:33:24.021+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:33:24.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.781 seconds
[2024-10-03T05:33:54.339+0000] {processor.py:157} INFO - Started process (PID=413) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:33:54.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:33:54.346+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:33:54.345+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:33:55.052+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:33:55.043+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:33:55.056+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:33:55.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.771 seconds
[2024-10-03T05:34:25.644+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:34:25.647+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:34:25.652+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:34:25.652+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:34:26.346+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:34:26.332+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:34:26.350+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:34:26.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.760 seconds
[2024-10-03T05:34:56.960+0000] {processor.py:157} INFO - Started process (PID=421) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:34:56.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:34:56.973+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:34:56.972+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:34:57.706+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:34:57.691+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:34:57.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:34:57.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.798 seconds
[2024-10-03T05:35:28.374+0000] {processor.py:157} INFO - Started process (PID=425) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:35:28.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:35:28.384+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:35:28.383+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:35:29.074+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:35:29.060+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:35:29.078+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:35:29.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.767 seconds
[2024-10-03T05:35:59.742+0000] {processor.py:157} INFO - Started process (PID=429) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:35:59.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:35:59.750+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:35:59.750+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:36:00.493+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:36:00.480+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:36:00.497+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:36:00.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.833 seconds
[2024-10-03T05:36:30.979+0000] {processor.py:157} INFO - Started process (PID=433) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:36:30.985+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:36:30.991+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:36:30.991+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:36:31.680+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:36:31.666+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:36:31.685+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:36:31.739+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.775 seconds
[2024-10-03T05:37:02.147+0000] {processor.py:157} INFO - Started process (PID=437) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:37:02.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:37:02.162+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:37:02.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:37:03.243+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:37:03.212+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:37:03.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:37:03.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.211 seconds
[2024-10-03T05:37:33.642+0000] {processor.py:157} INFO - Started process (PID=441) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:37:33.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:37:33.650+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:37:33.650+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:37:34.461+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:37:34.447+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:37:34.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:37:34.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.867 seconds
[2024-10-03T05:38:05.099+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:38:05.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:38:05.113+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:38:05.112+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:38:05.987+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:38:05.977+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:38:05.990+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:38:06.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.953 seconds
[2024-10-03T05:38:36.429+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T05:38:36.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T05:38:36.437+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:38:36.436+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:38:37.064+0000] {logging_mixin.py:151} INFO - [2024-10-03T05:38:37.043+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T05:38:37.067+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T05:38:37.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.699 seconds
[2024-10-03T06:32:53.983+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:32:54.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:32:54.084+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:32:54.081+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:33:14.890+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:33:14.852+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:33:14.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:33:15.451+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 21.537 seconds
[2024-10-03T06:34:10.961+0000] {processor.py:157} INFO - Started process (PID=154) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:34:10.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:34:10.967+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:34:10.967+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:34:11.620+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:34:11.607+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:34:11.624+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:34:11.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.703 seconds
[2024-10-03T06:34:44.084+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:34:44.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:34:44.103+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:34:44.102+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:34:44.931+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:34:44.919+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:34:44.934+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:34:44.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.901 seconds
[2024-10-03T06:35:15.096+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:35:15.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:35:15.104+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:35:15.103+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:35:15.817+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:35:15.806+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:35:15.821+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:35:15.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.761 seconds
[2024-10-03T06:35:46.259+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:35:46.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:35:46.269+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:35:46.268+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:35:47.203+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:35:47.192+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:35:47.208+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:35:47.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.004 seconds
[2024-10-03T06:36:18.348+0000] {processor.py:157} INFO - Started process (PID=389) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:36:18.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:36:18.362+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:36:18.362+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:36:19.008+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:36:18.998+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:36:19.012+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:36:19.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.709 seconds
[2024-10-03T06:40:27.358+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:40:27.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:40:27.366+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:40:27.365+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:40:45.008+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:40:44.945+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:40:45.021+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:40:45.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 18.709 seconds
[2024-10-03T06:41:32.749+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:41:32.752+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:41:32.757+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:41:32.757+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:41:33.804+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:41:33.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:41:33.809+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:41:33.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 1.122 seconds
[2024-10-03T06:42:12.570+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:42:12.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:42:12.626+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:42:12.621+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:42:14.880+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:42:14.828+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:42:14.887+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:42:14.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 2.448 seconds
[2024-10-03T06:42:48.892+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:42:48.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:42:48.926+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:42:48.924+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:42:51.284+0000] {logging_mixin.py:151} INFO - [2024-10-03T06:42:51.195+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:42:51.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:42:51.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch-data.py took 2.546 seconds
[2024-10-03T06:52:30.922+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:52:30.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:52:30.944+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:52:30.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:52:31.094+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:52:31.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:52:31.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:52:31.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.354 seconds
[2024-10-03T06:53:10.610+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:53:10.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:53:10.624+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:53:10.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:53:10.717+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:53:10.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:53:10.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:53:10.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.212 seconds
[2024-10-03T06:53:41.047+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:53:41.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:53:41.056+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:53:41.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:53:41.102+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:53:41.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:53:41.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:53:41.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.121 seconds
[2024-10-03T06:54:11.660+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:54:11.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:54:11.671+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:54:11.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:54:11.781+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:54:11.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:54:11.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:54:11.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.180 seconds
[2024-10-03T06:54:42.446+0000] {processor.py:186} INFO - Started process (PID=336) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:54:42.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:54:42.451+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:54:42.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:54:42.488+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:54:42.481+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:54:42.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:54:42.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.089 seconds
[2024-10-03T06:55:13.182+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:55:13.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:55:13.191+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:55:13.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:55:13.252+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:55:13.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:55:13.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:55:13.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.131 seconds
[2024-10-03T06:55:44.299+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:55:44.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:55:44.312+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:55:44.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:55:44.362+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:55:44.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:55:44.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:55:44.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.144 seconds
[2024-10-03T06:56:14.668+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:56:14.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:56:14.676+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:56:14.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:56:14.735+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:56:14.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:56:14.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:56:14.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.173 seconds
[2024-10-03T06:56:45.207+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:56:45.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:56:45.213+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:56:45.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:56:45.240+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:56:45.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:56:45.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:56:45.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.071 seconds
[2024-10-03T06:57:15.916+0000] {processor.py:186} INFO - Started process (PID=656) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:57:15.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:57:15.922+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:57:15.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:57:15.961+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:57:15.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:57:15.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:57:15.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.089 seconds
[2024-10-03T06:57:46.261+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:57:46.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:57:46.269+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:57:46.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:57:46.330+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:57:46.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:57:46.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:57:46.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.169 seconds
[2024-10-03T06:58:16.574+0000] {processor.py:186} INFO - Started process (PID=778) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:58:16.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:58:16.581+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:58:16.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:58:16.619+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:58:16.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:58:16.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:58:16.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.092 seconds
[2024-10-03T06:58:47.289+0000] {processor.py:186} INFO - Started process (PID=841) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:58:47.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:58:47.297+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:58:47.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:58:47.342+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:58:47.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 7, in <module>
    import secret as secret
ModuleNotFoundError: No module named 'secret'
[2024-10-03T06:58:47.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:58:47.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.110 seconds
[2024-10-03T06:59:07.000+0000] {processor.py:186} INFO - Started process (PID=895) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:59:07.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:59:07.005+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:59:07.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:59:07.071+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:59:07.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 59, in <module>
    "api_key": secret.api_key
               ^^^^^^
NameError: name 'secret' is not defined
[2024-10-03T06:59:07.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:59:07.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.123 seconds
[2024-10-03T06:59:37.710+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T06:59:37.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T06:59:37.728+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:59:37.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:59:37.850+0000] {logging_mixin.py:190} INFO - [2024-10-03T06:59:37.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 59, in <module>
    "api_key": secret.api_key
               ^^^^^^
NameError: name 'secret' is not defined
[2024-10-03T06:59:37.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T06:59:38.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.347 seconds
[2024-10-03T07:00:12.572+0000] {processor.py:186} INFO - Started process (PID=1008) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T07:00:12.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T07:00:12.579+0000] {logging_mixin.py:190} INFO - [2024-10-03T07:00:12.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T07:00:12.639+0000] {logging_mixin.py:190} INFO - [2024-10-03T07:00:12.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 59, in <module>
    "api_key": secret.api_key
               ^^^^^^
NameError: name 'secret' is not defined
[2024-10-03T07:00:12.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T07:00:12.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.131 seconds
[2024-10-03T07:00:43.688+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/fetch-data.py
[2024-10-03T07:00:43.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fetch-data.py for tasks to queue
[2024-10-03T07:00:43.693+0000] {logging_mixin.py:190} INFO - [2024-10-03T07:00:43.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fetch-data.py
[2024-10-03T07:00:43.728+0000] {logging_mixin.py:190} INFO - [2024-10-03T07:00:43.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fetch-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch-data.py", line 59, in <module>
    "api_key": secret.api_key
               ^^^^^^
NameError: name 'secret' is not defined
[2024-10-03T07:00:43.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch-data.py
[2024-10-03T07:00:43.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fetch-data.py took 0.077 seconds
